### ISSUE TITLE
Arrays for Tree building and querying

### ISSUE THREAD

**Issue by decardinb** [alyst/SpatialIndexing.jl#3]
Can we make the building and query of the RTree to accept Arrays? Then maybe make the Point and Rect Struct internal? I have 10 million or even more query points (in Array) and I always have to convert them to Points via Tuple before querying. This leads to excessive memory allocations in my loop (over 200 k allocations). 

It will be nice to have something similar to the API of [LibSpatialIndex.jl](https://github.com/JuliaGeo/LibSpatialIndex.jl) for creating and querying RTree.

Insertion
`LibSpatialIndex.insert!(rtree, 1, [0.,0.], [1.,1.])`

Query
`LibSpatialIndex.intersects(rtree, [1.,1.])`

**Comment by juliohm** [comment]
In Julia it is much more efficient to work with statically allocated objects such as tuples or StaticArrays.jl. I don't think it is a good idea to allow general vectors here, specially if performance is valued.

**Comment by decardinb** [comment]
@juliohm I agree with you. I have modified my code to work with tuples thus making it easier to use this package with my algorithm while getting good performance. Thanks.
