### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by juliohm** [alyst/SpatialIndexing.jl#5]
This package seems super well-written 👏🏽 thanks for the making it available.

I am having some difficulty understanding the arguments of the `RTree` constructor, even after reading the examples as suggested in the README. Could you please elaborate on the `K` and `V` arguments?

```julia
RTree{T,N}(::Type{V}; kwargs...) where {T,N,V} =    RTree{T,N,SpatialElem{T,N,Nothing,V}}(; kwargs...)
RTree{T,N}(::Type{K}, ::Type{V}; kwargs...) where {T,N,K,V} =    RTree{T,N,SpatialElem{T,N,K,V}}(; kwargs...)
```

**Comment by juliohm** [comment]
Also, could you please confirm that this is a good method for finding rectangles that intersect with a given rectangle?

```julia
import SpatialIndexing as SI

# create 1D R-tree with coordinates of type Float64
rtree = SI.RTree{Float64,1}(Int)

# create a rectangle to insert in the tree
rect = SI.Rect((0.,), (1.,))

# insert two rectangles with identifiers "1" and "2"
SI.insert!(rtree, rect, 1)
SI.insert!(rtree, rect, 2)

# query the tree for all rectangles intersecting the rect
itr = intersects_with(rtree, rect)

# select the first rectangle and retrieve its identifier
first(itr).val
```

**Comment by alyst** [comment]
I've just added docstring that clarifies that a bit.
These contructors create r-trees that store `SpatialElem{T,N,K,V}` values.
That is, each element of the tree stores MBR, optionally an identifier of type `K` and a value `V` of type V.

**Comment by alyst** [comment]
> Also, could you please confirm that this is a good method for finding rectangles that intersect with a given rectangle?

Yes, that looks correct.

**Comment by juliohm** [comment]
Thank you @alyst , can you just clarify the difference between an identifier and a value? Is it about the storage in the implementation where values are stored externally where identifiers are stored locally in memory together with the regions?

**Comment by alyst** [comment]
> Thank you @alyst , can you just clarify the difference between an identifier and a value?

In `SpatialElement{T,N,K,V}`, `V` is the user-defined information that is stored (in memory) in the r-tree element, and `K` is an optional identifier of the element (use can also set it to `Nothing`).
At the moment it's the user responsibility to provide the identifiers and make sure they are unique.
So far RTree check the identifier only in `findfirst()` method to guarantee that leaf returned is indeed for the element with the given id, and not just some element with the duplicate MBR (if `K` is `Nothing`, these checks are not applied).

For example, if you use R-Tree to index different geometrical objects (rectangles, ellipses, splines) of some 2D scene, then V would define the exact geometry (center and radius of the circle etc), and K would define the unique identifier of that circle among all the elements of the scene.

Potentially, it should be easy to make `RTree{T,N,K,V}` support the `AbstractDict{K,V}` interface to quickly get the elements by id, but that's not implemented.

Just a bit of a broader context. I've tried to make the SpatialIndexing.jl a generic implementation of spatial indexing, but my only real use case was the multiobjective optimization in [BlackBoxOptim.jl](https://github.com/robertfeldt/BlackBoxOptim.jl).
Beyond that I didn't have the resources to polish the API and apply it to the other real use cases, but I would totally support that.
So if you have a particular application in mind, and you realize that some functionality is missing or some API could be improved, feel free to propose the changes (most preferably as PRs, as at the moment I cannot allocate a lot of resources into the development of this package).
