### ISSUE TITLE
Update to Project.toml

### ISSUE THREAD

**Issue by juliohm** [alyst/SpatialIndexing.jl#6]
Would a PR be welcome to update from REQUIRE to Project.toml? Julia's new package manager is superb and it would be nice to update this accordingly. BTW, I love the fact that you managed to write such a useful package without any extra dependency 🥇

**Comment by alyst** [comment]
Thanks for your kind evaluation of the package! :)
Sure, I will be glad to accept PRs with bugfixes and enhancements.
